# JuliaOS Agents Configuration

# Storage settings
[storage]
path = "db/agents_state.json"
backup_enabled = true
backup_count = 5
auto_persist = true

# Agent settings
[agent]
max_task_history = 100
xp_decay_rate = 0.999
default_sleep_ms = 1000
paused_sleep_ms = 500
auto_restart = false
monitoring_enabled = true
monitor_interval = 30
max_stall_seconds = 300

# Metrics settings
[metrics]
enabled = true
collection_interval = 60
retention_period = 86400  # 24 hours in seconds

# Swarm settings
[swarm]
enabled = true
backend = "memory"  # Options: none, memory, redis, nats, zeromq
connection_string = ""
default_topic = "juliaos.swarm"

# LLM settings
[llm]
default_provider = "openai"
default_model = "gpt-4o-mini"
default_temperature = 0.7
default_max_tokens = 1024
